/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package housing

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        //val service = ApplicationService();
        //assertNotNull(service.greeting, "app should have a greeting")
        
    }
}
